
const FORECAST_ACTIONS = {
  REQUEST_FORECAST: 'REQUEST_FORECAST',
  ERROR_REQUESTING_FORECAST: 'ERROR_REQUESTING_FORECAST',
  SET_FORECAST: 'SET_FORECAST'
};

const LOCATION_ACTIONS = {
  SET_LOCATION_NAME: 'SET_LOCATION_NAME',
  REMOVE_LOCATION_DAY: 'REMOVE_LOCATION_DAY',
  SET_LOCATION_DAY: 'SET_LOCATION_DAY'
};

export default {
  ...FORECAST_ACTIONS,
  ...LOCATION_ACTIONS
};
